name: "Xeol End-of-Life (EOL) Scan"
description: "Scan docker containers with Xeol for End-of-Life (EOL) packages"
branding:
  color: blue
  icon: check-circle
inputs:
  image:
    description: 'The image to scan. This option is mutually exclusive with "path" and "sbom". '
    required: false
  path:
    description: 'The path to scan. This option is mutually exclusive with "image" and "sbom".'
    required: false
  sbom:
    description: 'The SBOM file to scan. This option is mutually exclusive with "path" and "image".'
    required: false
  fail-build:
    description: "Set to false to avoid failing based on finding an EOL package. Default is to fail when any EOL package is found."
    required: false
    default: "true"
  output-format:
    description: 'Set the output parameter after successful action execution. Valid choices are "json" and "table".'
    required: false
    default: "table"
  api-key:
    description: "The Xeol API key to use for scanning."
    required: false
outputs:
  json:
    description: "Path to a JSON report file for the image"
runs:
  using: "node16"
  main: "dist/index.js"
